import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables');
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Comprehensive product data for all 11 categories
const comprehensiveProducts = [
  // Fashion and Apparel (10 products)
  {
    id: 'fashion-001',
    title: 'Men\'s Classic Denim Jeans',
    description: 'Comfortable straight-fit denim jeans for everyday wear',
    price: 89.99,
    category: 'fashion',
    image_url: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop',
    stock_quantity: 50,
    status: 'active',
    vendor_id: '6fac5f0f-9522-49c2-a131-60bf330545d5',
    brand: 'Levi\'s',
    is_flash_sale: true,
    is_clearance: false,
    is_trending: true,
    is_new_this_week: false,
    is_top_selling: true,
    is_featured: false,
    is_hot_deal: false,
    is_dont_miss: false,
    original_price: 119.99,
    discount_percentage: 25,
    rating_average: 4.5,
    rating_count: 234,
    meta_title: 'Men\'s Classic Denim Jeans - VendorHub',
    meta_description: 'Premium quality denim jeans for men. Comfortable fit and durable construction.',
    search_keywords: ['jeans', 'denim', 'men', 'fashion', 'pants'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'fashion-002',
    title: 'Women\'s Elegant Evening Dress',
    description: 'Stunning black evening dress perfect for special occasions',
    price: 149.99,
    category: 'fashion',
    image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&h=400&fit=crop',
    stock_quantity: 25,
    status: 'active',
    vendor_id: '6fac5f0f-9522-49c2-a131-60bf330545d5',
    brand: 'Zara',
    is_flash_sale: false,
    is_clearance: true,
    is_trending: false,
    is_new_this_week: true,
    is_top_selling: false,
    is_featured: true,
    is_hot_deal: false,
    is_dont_miss: false,
    original_price: 199.99,
    discount_percentage: 25,
    rating_average: 4.7,
    rating_count: 156,
    meta_title: 'Women\'s Elegant Evening Dress - VendorHub',
    meta_description: 'Beautiful evening dress for special occasions. Elegant design and premium fabric.',
    search_keywords: ['dress', 'evening', 'women', 'fashion', 'formal'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'fashion-003',
    title: 'Nike Air Force 1 Sneakers',
    description: 'Classic white leather sneakers with iconic Nike design',
    price: 129.99,
    category: 'fashion',
    image_url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=400&fit=crop',
    stock_quantity: 75,
    status: 'active',
    vendor_id: '6fac5f0f-9522-49c2-a131-60bf330545d5',
    brand: 'Nike',
    is_flash_sale: false,
    is_clearance: false,
    is_trending: true,
    is_new_this_week: false,
    is_top_selling: true,
    is_featured: false,
    is_hot_deal: true,
    is_dont_miss: false,
    original_price: 149.99,
    discount_percentage: 13,
    rating_average: 4.8,
    rating_count: 445,
    meta_title: 'Nike Air Force 1 Sneakers - VendorHub',
    meta_description: 'Iconic Nike Air Force 1 sneakers. Classic design meets modern comfort.',
    search_keywords: ['sneakers', 'nike', 'shoes', 'fashion', 'white'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'fashion-004',
    title: 'Luxury Leather Handbag',
    description: 'Premium leather handbag with gold hardware and spacious interior',
    price: 299.99,
    category: 'fashion',
    image_url: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=400&fit=crop',
    stock_quantity: 30,
    status: 'active',
    vendor_id: '6fac5f0f-9522-49c2-a131-60bf330545d5',
    brand: 'Michael Kors',
    is_flash_sale: false,
    is_clearance: false,
    is_trending: false,
    is_new_this_week: false,
    is_top_selling: false,
    is_featured: true,
    is_hot_deal: false,
    is_dont_miss: true,
    original_price: 399.99,
    discount_percentage: 25,
    rating_average: 4.6,
    rating_count: 187,
    meta_title: 'Luxury Leather Handbag - VendorHub',
    meta_description: 'Premium leather handbag with elegant design. Perfect for daily use or special occasions.',
    search_keywords: ['handbag', 'leather', 'luxury', 'fashion', 'accessories'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'fashion-005',
    title: 'Men\'s Casual Cotton T-Shirt',
    description: 'Soft cotton t-shirt in various colors, perfect for casual wear',
    price: 24.99,
    category: 'fashion',
    image_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop',
    stock_quantity: 100,
    status: 'active',
    vendor_id: '6fac5f0f-9522-49c2-a131-60bf330545d5',
    brand: 'H&M',
    is_flash_sale: true,
    is_clearance: false,
    is_trending: false,
    is_new_this_week: true,
    is_top_selling: false,
    is_featured: false,
    is_hot_deal: false,
    is_dont_miss: false,
    original_price: 34.99,
    discount_percentage: 29,
    rating_average: 4.3,
    rating_count: 567,
    meta_title: 'Men\'s Casual Cotton T-Shirt - VendorHub',
    meta_description: 'Comfortable cotton t-shirt for everyday wear. Available in multiple colors.',
    search_keywords: ['tshirt', 'cotton', 'men', 'fashion', 'casual'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  // Add more products here for other categories...
  // Electronics (10 products)
  {
    id: 'electronics-001',
    title: 'Samsung Galaxy S24 Ultra',
    description: 'Latest flagship smartphone with advanced AI features',
    price: 1399.99,
    category: 'electronics',
    image_url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&h=400&fit=crop',
    stock_quantity: 40,
    status: 'active',
    vendor_id: '6fac5f0f-9522-49c2-a131-60bf330545d5',
    brand: 'Samsung',
    is_flash_sale: true,
    is_clearance: false,
    is_trending: true,
    is_new_this_week: true,
    is_top_selling: false,
    is_featured: true,
    is_hot_deal: false,
    is_dont_miss: false,
    original_price: 1599.99,
    discount_percentage: 13,
    rating_average: 4.8,
    rating_count: 567,
    meta_title: 'Samsung Galaxy S24 Ultra - VendorHub',
    meta_description: 'Latest Samsung flagship with AI features. Advanced camera and performance.',
    search_keywords: ['samsung', 'smartphone', 'android', 'electronics', 'mobile'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'electronics-002',
    title: 'MacBook Pro 16-inch M3',
    description: 'Powerful laptop for professionals with M3 chip',
    price: 2999.99,
    category: 'electronics',
    image_url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop',
    stock_quantity: 15,
    status: 'active',
    vendor_id: '6fac5f0f-9522-49c2-a131-60bf330545d5',
    brand: 'Apple',
    is_flash_sale: false,
    is_clearance: false,
    is_trending: true,
    is_new_this_week: false,
    is_top_selling: true,
    is_featured: true,
    is_hot_deal: false,
    is_dont_miss: false,
    original_price: 3299.99,
    discount_percentage: 9,
    rating_average: 4.9,
    rating_count: 234,
    meta_title: 'MacBook Pro 16-inch M3 - VendorHub',
    meta_description: 'Professional laptop with M3 chip. Ultimate performance for creative professionals.',
    search_keywords: ['macbook', 'laptop', 'apple', 'electronics', 'computer'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  // Beauty and Personal Care (sample products)
  {
    id: 'beauty-001',
    title: 'Fenty Beauty Foundation',
    description: 'Full-coverage foundation with 50 inclusive shades',
    price: 38.99,
    category: 'beauty',
    image_url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop',
    stock_quantity: 60,
    status: 'active',
    vendor_id: '6fac5f0f-9522-49c2-a131-60bf330545d5',
    brand: 'Fenty Beauty',
    is_flash_sale: false,
    is_clearance: false,
    is_trending: true,
    is_new_this_week: false,
    is_top_selling: true,
    is_featured: false,
    is_hot_deal: false,
    is_dont_miss: false,
    original_price: 42.99,
    discount_percentage: 9,
    rating_average: 4.7,
    rating_count: 1234,
    meta_title: 'Fenty Beauty Foundation - VendorHub',
    meta_description: 'Full-coverage foundation with inclusive shade range. Long-lasting and comfortable wear.',
    search_keywords: ['foundation', 'makeup', 'beauty', 'fenty', 'cosmetics'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  // Add more sample products for other categories...
  // Home and Kitchen
  {
    id: 'home-001',
    title: 'KitchenAid Stand Mixer',
    description: 'Professional stand mixer for baking and cooking',
    price: 399.99,
    category: 'home',
    image_url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop',
    stock_quantity: 20,
    status: 'active',
    vendor_id: '6fac5f0f-9522-49c2-a131-60bf330545d5',
    brand: 'KitchenAid',
    is_flash_sale: false,
    is_clearance: false,
    is_trending: false,
    is_new_this_week: false,
    is_top_selling: false,
    is_featured: true,
    is_hot_deal: false,
    is_dont_miss: false,
    original_price: 499.99,
    discount_percentage: 20,
    rating_average: 4.8,
    rating_count: 567,
    meta_title: 'KitchenAid Stand Mixer - VendorHub',
    meta_description: 'Professional stand mixer perfect for baking. Powerful motor and multiple attachments.',
    search_keywords: ['mixer', 'kitchenaid', 'baking', 'home', 'kitchen'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  // Food and Beverages
  {
    id: 'food-001',
    title: 'Organic Avocado Box',
    description: 'Fresh organic avocados, perfectly ripe and ready to eat',
    price: 24.99,
    category: 'food',
    image_url: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=400&fit=crop',
    stock_quantity: 50,
    status: 'active',
    vendor_id: '6fac5f0f-9522-49c2-a131-60bf330545d5',
    brand: 'Organic Farms',
    is_flash_sale: true,
    is_clearance: false,
    is_trending: false,
    is_new_this_week: true,
    is_top_selling: false,
    is_featured: false,
    is_hot_deal: false,
    is_dont_miss: false,
    original_price: 29.99,
    discount_percentage: 17,
    rating_average: 4.6,
    rating_count: 234,
    meta_title: 'Organic Avocado Box - VendorHub',
    meta_description: 'Fresh organic avocados delivered to your door. Perfect for healthy meals and snacks.',
    search_keywords: ['avocado', 'organic', 'fresh', 'food', 'healthy'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  // Continue with more categories...
];

export async function insertBulkProducts() {
  try {
    console.log('Starting bulk product insertion...');
    
    const { data, error } = await supabase
      .from('products')
      .insert(comprehensiveProducts);
    
    if (error) {
      console.error('Error inserting products:', error);
      throw error;
    }
    
    console.log('Successfully inserted products:', data);
    return { success: true, count: comprehensiveProducts.length };
  } catch (error) {
    console.error('Bulk insert failed:', error);
    throw error;
  }
}